# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: “tDCS Database”
email: admin@interimm.org
description: "Community Driven tDCS Research Database"
# baseurl: "/hub" # the subpath of your site, e.g. /blog
# url: "http://interimm.org" # the base hostname & protocol for your site
twitter_username:
github_username: tdcs-db


#
subscribe:
   title: Subscribe
   link: http://tdcs-db.github.io

# Site Manager

author:
  name: tDCS-DB


# Build settings
markdown: kramdown

staticman: https://dev.staticman.net/v3/entry/github/tdcs-db/tdcs-db.github.io/master/research